---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# Pupilla

<!-- badges: start -->
<!-- badges: end -->

An R package for the processing and analysis of eye-tracking and
pupillometry data.

## Installation

The package is currently available through
[GitHub](https://github.com/). The installation requires the R package
`remotes`.

``` r
# install.packages("remotes")
remotes::install_github("EBlini/Pupilla")
```

## Scope

This is a collection of functions and wrappers that are useful for
preprocessing and analysis of eyetracking data, with a special focus on
pupillometry. Functions are generally hardware-agnostic, and have been designed for data collected through third-part experiment builders such as
OpenSesame. All functions are to be considered under development: all
requests or suggestions are more than welcome, :) .

For useful references, and an example of the results of these functions,
see [Blini and Zorzi,
2023](https://link.springer.com/article/10.3758/s13423-022-02192-z) and [Blini, Arrighi, and Anobile, 2024](https://www.nature.com/articles/s41598-024-78772-x).

